openapi: 3.1.0
info:
  title: hiyoko
  description: |
    hiyoko api
  version: 0.0.0
  termsOfService: https://hiyoko.com
  contact:
    name: Hiyoko API Team
    email: apiteam@hiyoko
    url: https://hiyoko.com
servers:
  - url: https://api.lvh.me
    description: local api
  - url: https://dev-api.hiyoko.com
    description: dev server api
security:
  - AuthApiKey: [ ]
tags:
  # camelCase
  - name: auth
  - name: user
paths:
  /v1/register:
    $ref: './paths/v1/register.yml'
  /v1/me:
    $ref: './paths/v1/me.yml'
components:
  securitySchemes:
    AuthApiKey:
      type: http
      scheme: bearer
      bearerFormat: JWT
