name: Pint Check

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - '**.php'

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Dry run Pint
        uses: aglipanci/laravel-pint-action@2.1.0
